# Generated by Django 3.2.11 on 2022-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='name site')),
                ('site_url', models.CharField(max_length=200, verbose_name='Domain site')),
                ('address', models.CharField(max_length=200, verbose_name='Address site')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone site')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='fax site')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='email site')),
                ('copy_right', models.TextField(verbose_name='Text copy right site')),
                ('about_us_text', models.TextField(verbose_name='Text inWith our site')),
                ('site_logo', models.ImageField(upload_to='images/site-setting/', verbose_name='logo site')),
                ('is_main_setting', models.BooleanField(verbose_name='Settings Main')),
            ],
            options={
                'verbose_name': 'Settings site',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
