# Generated by Django 3.2.11 on 2022-02-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_auto_20220220_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.CharField(max_length=200, verbose_name='link')),
                ('url_title', models.CharField(max_length=200, verbose_name='Title link')),
                ('description', models.TextField(verbose_name='descriptionslide in')),
                ('image', models.ImageField(upload_to='images/sliders', verbose_name='Image slide in')),
            ],
            options={
                'verbose_name': 'slide in',
                'verbose_name_plural': 'slide in ',
            },
        ),
    ]
