# Generated by Django 3.2.7 on 2021-12-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('full_name', models.CharField(max_length=300, verbose_name='name and name family')),
                ('message', models.TextField(verbose_name='Text contact us')),
                ('is_read_by_admin', models.BooleanField(verbose_name='Read by admin')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Creation')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Text Response contact us')),
            ],
            options={
                'verbose_name': 'contact us',
                'verbose_name_plural': 'list contact us',
            },
        ),
    ]
